### ISSUE TITLE
Place names, despite being deleted in the dasboard are unable to be used again.

### ISSUE THREAD

**Issue by Aitolda** [vircadia/Iamus#83]
![failed](https://user-images.githubusercontent.com/21160271/114284867-be1dba80-9a07-11eb-85ae-a808f08d6344.png)

I've migrated my domain to a new location and at some point deleted the original placename, now I am unable to use the same name again.

**Comment by Misterblue** [comment]
This problem seems to be fixed in Iamus 2.4.4
