### ISSUE TITLE
Places thumbnail and images: ratio and file size

### ISSUE THREAD

**Issue by AleziaKurdis** [vircadia/Iamus#86]
In order to build any explore app from the place API (GET api/v1/places)

RATIO:
It would be a good thing to indicate which ratio the images need to be.
It's better if all users are invited to add pictures with the same standard. The eventual applications that will use those pictures will definitely need a consistent format. If people know before, they might not get the surprise to see their picture completely stretched in any application using them.

I would suggest the **16:9** format since it's the standard of a majority of monitors and official media.

We basically just need to indicate the recommended ratio in the UI where we can enter pictures in the dashboard. No need of any file validation for that. It will be the responsibility of the user to stick with the standard that will be indicated to get good results for the place or profile. (But they do need to know what is the standard)

FILE SIZE:
It would be good to have a file size check when we save any new picture URL in the dashboard (and in the different API).
because someone could put a very fat picture file that can cause serious performance issues in the different applications using those API. (I don't know if such mechanism is already in the system or not, I prefer to mention it if it's not the case)

**Comment by Misterblue** [comment]
The metaverse-server only saves the URL of the thumbnails and images and thus never sees the actual image (its size or its ratio). These changes need to go into the Dashboard.

**Comment by AleziaKurdis** [comment]
Open an issue on the  vircadia / project-iamus-dashboard 
https://github.com/vircadia/project-iamus-dashboard/issues/42
