### ISSUE TITLE
Delete place is failing. (even recently created places)

### ISSUE THREAD

**Issue by AleziaKurdis** [vircadia/Iamus#88]
When we try to delete a Place, we systematically get this error:

**Failed to delete place: **_{placeId}_**
Error code 3
The full error is shown below:
Target place not found**

This happens even on recently created places.

**Comment by Misterblue** [comment]
There seems to be two ways of deleting places: "DELETE /api/v1/places/:placeId" and "DELETE /api/v1/user/places/:placeId". For this bug, one works and one doesn't work.
Fix is in process.

**Comment by Misterblue** [comment]
Fixed in version 2.4.3
