### ISSUE TITLE
Places api: domain data keeps returning "active" = true, even after they get shut down.

### ISSUE THREAD

**Issue by AleziaKurdis** [vircadia/Iamus#93]
Places api: domain data keeps returning "active" = true, even after they get shut down.

If I shutdown all my domain, They are still considered as "active" = true in the place API.

**Comment by AleziaKurdis** [comment]
The probleme is worst than that.
the place in the code where the "domain.active" value is supposed to be reset to false when a domain stop hearthbeating
is also responsible to reset the user count.
But clearly, this piece of code is never called for any reason.

So this mean that not only inactive domain keep to be return as active, but also it might happen that a domain get stopped with people present in it, and the count will be stuck for ever. In such a case, a domain with some user will be stuck in the list for ever.

Also the date format used for the "place.current_last_update_time" and "domain.time_of_last_heartbeat" is impossible to work with (programatically speaking). The vircadia's javascript is unable to parse it using Date.parse() or new Date(). (it work with a web page but not in Vircadia)
I don't think we want to have to do extra-parsing here. Why don't return direct the unix epoch time, (or both if you absolutely what a date format that a human can read.)

All this left no solution to exclude the inactive domains and this is bad for any explore app we would like to build over this.

**Comment by ctrlaltdavid** [comment]
From Alezia...
![active-and-date-problems](https://user-images.githubusercontent.com/7455448/125856517-cde5f512-0a46-4b7c-ab9e-e910f8ecda82.png)

**Comment by Misterblue** [comment]
The active/user reset I will debug and test.

The date format was chosen to be a human readable string (it's JSON after all) and it is an un-ambiguious date standard format (with time zone, etc). I'm surprized all languages don't have a parser for it.

**Comment by AleziaKurdis** [comment]
I've been very surprized either, especially that it's between 2 versions of javascript, (web versus the vircadia script) to parse a date format that is ISO.
If the piece of code that sets the active state is robust enough maybe we can keep the current format. 
The only functional use I know from the heartbeat date is to determine if the server is active or not. (which is what the active state represente)
But if you know other date field in the API, maybe we should see what use can be done from these. If it' something that we might use for calculation, it might cause a problem with the vircadia's javascipt (We would like to avoid people to reinvent the wheel by coding their own date parser)

**Comment by SilverfishVR** [comment]
hmm, I remember trying to parse ISO 8601 date strings like that in vircadia with Date.Parse() but it always returned NaN, I assumed it was a me problem since I'm not really a coder, I just did what the interwebs told me would work.

**Comment by Misterblue** [comment]
Internally to Iamus, these dates are kept as Javascript Date objects so any formating is possible. Iamus uses the Date.toISOString() method to convert it to a string for JSON output.

Date.parse() is documented to take a "simplified ISO" date string (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/parse#date_time_string_format) but it does return NaN if it doesn't like the date string.  I don't know what Vircadia script is using. HiFi could have built their own parser for some reason.

**Comment by AleziaKurdis** [comment]
To me, a date should be kept as a unix timestamp as long as possible until it is used to display a date to a human ( then we format it for the display.)
Have it formated to have to parsed to be used is only increasing the risk of incidents.
If you read about Date.Parse(), you will discover that it's not the most trustable thing in this world. Some people just avoid it.
Maybe we can expose both format? Having it humanly readable is to me just to ease the manual testing of the API. Maybe we could expose the ISO formated date only in debug mode?
