### ISSUE TITLE
Domain "active" flag doesn't go false when domain stops heartbeating

### ISSUE THREAD

**Issue by Misterblue** [vircadia/Iamus#95]
When fetching domain JSON information, the "active" field is usually "true" but it doesn't go to "false" when the domain stops heartbeating.

**Comment by digisomni** [comment]
There should be a time since last check-in setting perhaps to indicate an inactive domain. Does Iamus do regular checks against all domains with active: true to see if that's still the case?

**Comment by Misterblue** [comment]
Every few minutes, Iamus checks for all domains that haven't heartbeated in the last 10 minutes (a metaverse-server configurable parameter) and it zeros that attendance and active flags if so. The goal is for a domain that is not heartbeating to be empty and inactive. There is also some logic for Places to make them set their attendance to zero if either the beacon is not updating or the domain is inactive.

Looking at the code, I see the bug (not resetting the active flag) so the fix is not far off.
