### ISSUE TITLE
Non connected users appear to be counted 2 times...

### ISSUE THREAD

**Issue by AleziaKurdis** [vircadia/Iamus#98]
I don't know if it's the "**_domain server_**" or the "**_metaverse server_**" that has the bug, but a user that is not connected to an account is counted 2 time in the number of user on a domain/place.

**To reproduce:**
- As a **NON-connected** user, go in a domain where you know that you will be alone. The place API will **return 2** as number of user in the Place and the Domain.

- Wait 5 minutes

- As a **connected** user, go in a domain where you know that you will be alone. The place API will **return 1** as number of user in the Place and the Domain.

**Comment by Misterblue** [comment]
This is an Iamus bug. Testing found that Iamus's interpretation of what the domain-server sends is wrong. The heartbeat sends "num_users" and "num_anon_users" and, if there is one anon user, those are both returned at "1". That is, "num_users" seems to be the total number of users and "num_anon_users" is the number of those users that are anonymous. Iamus mis-interpreted it as "num_users" being the number of logged in users.
